-- Product seed data derived from frontend/src/data/products.js
-- Compatible with the `products` table created in database_setup.sql

TRUNCATE TABLE products RESTART IDENTITY;

INSERT INTO products (
    id,
    name,
    name_hi,
    price,
    category,
    description,
    description_hi,
    manufacturer,
    origin,
    ingredients,
    health_benefits,
    health_benefits_hi,
    certifications,
    hsn_code,
    gst_rate,
    variants,
    stock,
    image,
    images,
    created_at,
    updated_at
) VALUES
('1', 'Mustard Oil (Kacchi Ghani)', 'सरसों का तेल (कच्ची घानी)', 190, 'Oils',
 'Authentic Kacchi Ghani Mustard Oil, cold-pressed to retain its natural ''Jhaanjh'' (pungency). Extracted from premium mustard seeds of Rajasthan, it is the soul of North Indian and Bengali kitchens.',
 'असली कच्ची घानी सरसों का तेल, जो अपने प्राकृतिक तीखेपन (झांझ) को बरकरार रखता है। राजस्थान के प्रीमियम बीजों से निकाला गया, यह उत्तर भारतीय और बंगाली व्यंजनों की जान है।',
 'Madhuban Oils Co.', 'Rajasthan, India',
 '["Cold-pressed mustard oil"]',
 '["Rich in MUFA for heart health","Natural anti-bacterial agent for food preservation","Stimulates digestion and circulation","Traditional remedy for respiratory relief when used topically","Good for skin and hair when used topically"]',
 '["हृदय स्वास्थ्य के लिए MUFA से भरपूर","भोजन संरक्षण के लिए प्राकृतिक एंटी-बैक्टीरियल गुण","पाचन और रक्त संचार को उत्तेजित करता है","श्वसन राहत के लिए पारंपरिक उपचार","त्वचा और बालों के लिए फायदेमंद"]',
 '["FSSAI"]', '1514', 5,
 '[{"id":"v1a","label":"1 L","price":195},{"id":"v1b","label":"2 L","price":390},{"id":"v1c","label":"5 L","price":950}]',
 25, '/assets/products/1_Mustard_Oil_0.png',
 '["/assets/products/1_Mustard_Oil_0.png","/assets/products/1_Mustard_Oil.png","/assets/products/1_Mustard_Oil_1.png","/assets/products/2_Groundnut_Oil.png","/assets/products/2_Groundnut_Oil_1.png"]',
 NOW(), NOW()),

('2', 'Groundnut Oil (Mugfali)', 'मूंगफली का तेल', 70, 'Oils',
 'Pure cold-pressed groundnut oil sourced from Saurashtra. It has a high smoke point and a delicate nutty flavor that doesn''t overpower the food.',
 'सौराष्ट्र से प्राप्त शुद्ध कोल्ड-प्रेस्ड मूंगफली का तेल। इसका स्मोक पॉइंट उच्च है और स्वाद हल्का नटी है जो खाने के असली स्वाद को दबने नहीं देता।',
 'Madhuban Oils Co.', 'Gujarat, India',
 '["Cold-pressed groundnut oil"]',
 '["Contains Phytosterols that help lower cholesterol","Rich in Vitamin E, a powerful antioxidant","Resistant to oxidation at high temperatures","Promotes skin health and anti-aging","High smoke point for frying"]',
 '["कोलेस्ट्रॉल कम करने वाले फाइटोस्टेरॉल युक्त","विटामिन ई (एंटीऑक्सीडेंट) का समृद्ध स्रोत","उच्च तापमान पर सुरक्षित (ऑक्सीकरण प्रतिरोधी)","त्वचा के स्वास्थ्य और एंटी-एजिंग में सहायक","तलने के लिए उच्च स्मोक पॉइंट"]',
 '["FSSAI"]', '1508', 5,
 '[{"id":"v2a","label":"250 ml","price":75},{"id":"v2b","label":"500 ml","price":150},{"id":"v2c","label":"1 L","price":300}]',
 18, '/assets/products/2_Groundnut_Oil.png',
 '["/assets/products/2_Groundnut_Oil.png","/assets/products/2_Groundnut_Oil_1.png"]',
 NOW(), NOW()),

('3', 'Coconut Oil (Nariyala)', 'नारियल का तेल', 150, 'Oils',
 'Cold-pressed coconut oil — excellent for cooking and hair/skin care.',
 'कोल्ड-प्रेस्ड शुद्ध नारियल का तेल — खाना पकाने और बाल/त्वचा के लिए उत्कृष्ट।',
 'Madhuban Oils Co.', 'Kerala, India',
 '["100% coconut oil"]',
 '["Contains MCTs for instant energy boost","Lauric acid supports immune system health","Excellent for thyroid and metabolic health","Anti-fungal and anti-microbial properties","Promotes hair and skin health","Contains medium-chain triglycerides"]',
 '["त्वरित ऊर्जा के लिए MCTs से भरपूर","लौरिक एसिड रोग प्रतिरोधक क्षमता बढ़ाता है","थायराइड और मेटाबॉलिज्म के लिए बेहतरीन","एंटी-फंगल और एंटी-माइक्रोबियल गुण","बाल और त्वचा के स्वास्थ्य को बढ़ावा देता है","मीडियम-चेन ट्राइग्लिसराइड्स से भरपूर"]',
 '["FSSAI","Organic"]', '1513', 5,
 '[{"id":"v3a","label":"250 ml","price":250},{"id":"v3b","label":"500 ml","price":495},{"id":"v3c","label":"1 L","price":990}]',
 12, '/assets/products/coconut_1.png',
 '["/assets/products/coconut_1.png","/assets/products/coconut_2.png"]',
 NOW(), NOW()),

('4', 'Sesame Oil (Til)', 'तिल का तेल', 200, 'Oils',
 'Cold-pressed sesame (til) oil — rich, nutty flavour ideal for seasoning and cooking.',
 'कोल्ड-प्रेस्ड तिल का तेल — समृद्ध, नट्टी स्वाद, खाना पकाने और सीज़निंग के लिए उपयुक्त।',
 'Madhuban Oils Co.', 'Gujarat, India',
 '["100% cold-pressed sesame oil"]',
 '["Good source of antioxidants","May support heart health"]',
 '["एंटीऑक्सीडेंट का अच्छा स्रोत","हृदय स्वास्थ्य में सहायक हो सकता है"]',
 '["FSSAI"]', '1509', 5,
 '[{"id":"v4a","label":"250 ml","price":200},{"id":"v4b","label":"500 ml","price":380},{"id":"v4c","label":"1 L","price":720}]',
 9, '/assets/products/sesame_1.png',
 '["/assets/products/sesame_1.png","/assets/products/sesame_2.png"]',
 NOW(), NOW()),

('5', 'Sunflower Oil (Sursajmukhi)', 'सूरजमुखी का तेल', 95, 'Oils',
 'A light and healthy cooking oil that is easy on the stomach. Our sunflower oil is refined to ensure a high smoke point, making it ideal for the diverse Indian kitchen.',
 'एक हल्का और स्वस्थ खाना पकाने का तेल जो पाचन में आसान है। यह तेल भारतीय रसोई की विविध जरूरतों के लिए बनाया गया है।',
 'Madhuban Oils Co.', 'Madhya Pradesh, India',
 '["Refined Sunflower Oil"]',
 '["Extremely rich in Vitamin E for immunity","Low in saturated fats, good for weight management","Contains Lecithin which helps lower cholesterol","Promotes healthy hair and prevents thinning"]',
 '["इम्युनिटी के लिए विटामिन ई से भरपूर","वजन घटाने के लिए कम सैचुरेटेड फैट","कोलेस्ट्रॉल कम करने में सहायक लेसिथिन युक्त","बालों को झड़ने से रोकने में मददगार"]',
 '["FSSAI"]', '1512', 5,
 '[{"id":"v5a","label":"500 ml","price":95},{"id":"v5b","label":"1 L","price":180},{"id":"v5c","label":"5 L","price":700}]',
 14, '/assets/products/sunflower_1.png',
 '["/assets/products/sunflower_1.png","/assets/products/sunflower_2.png"]',
 NOW(), NOW()),

('6', 'Flaxseed Oil (Tisi)', 'अलसी(तीसी) का तेल', 320, 'Oils',
 'A vegetarian powerhouse of Omega-3. This cold-pressed oil is made from high-quality Alsi seeds from Punjab, perfect for those seeking a plant-based health supplement.',
 'ओमेगा-3 का शाकाहारी खजाना। पंजाब के उच्च गुणवत्ता वाले अलसी के बीजों से बना यह तेल स्वास्थ्य सप्लीमेंट के रूप में उत्तम है।',
 'Madhuban Oils Co.', 'Punjab, India',
 '["100% Cold-pressed Flaxseed Oil"]',
 '["Highest plant source of Alpha-linolenic acid (Omega-3)","Reduces inflammation in joints and arteries","Improves skin smoothness and hydration","Supports hormonal balance in women"]',
 '["ओमेगा-3 (ALA) का उच्चतम शाकाहारी स्रोत","जोड़ों और धमनियों की सूजन को कम करता है","त्वचा की कोमलता और नमी को सुधारता है","महिलाओं में हार्मोनल संतुलन का समर्थन करता है"]',
 '["FSSAI"]', '1510', 5,
 '[{"id":"v6a","label":"250 ml","price":320},{"id":"v6b","label":"500 ml","price":600},{"id":"v6c","label":"1 L","price":1100}]',
 7, '/assets/products/Flaxseed_1.png',
 '["/assets/products/Flaxseed_1.png","/assets/products/Flaxseed_2.png"]',
 NOW(), NOW()),

('7', 'Turmeric Powder (Haldi)', 'हल्दी पाउडर', 80, 'Spices',
 'High-Curcumin (min 3.5%) Turmeric powder sourced from Salem. Guaranteed free from lead chromate and artificial starch.',
 'सेलम से प्राप्त उच्च करक्यूमिन युक्त हल्दी पाउडर। मिलावट रहित और शुद्ध औषधीय गुणों से भरपूर।',
 'Madhuban Spices', 'Tamil Nadu, India',
 '["100% Pure Ground Turmeric"]',
 '["Powerful natural anti-inflammatory agent","Enhances immunity against seasonal infections","Supports liver detoxification","Promotes wound healing and healthy skin"]',
 '["शक्तिशाली प्राकृतिक सूजन-रोधी","मौसमी संक्रमणों के खिलाफ इम्युनिटी बढ़ाता है","लिवर की सफाई में सहायक","घाव भरने और त्वचा निखारने में मददगार"]',
 '["Organic","FSSAI"]', '0910', 5,
 '[{"id":"v7a","label":"100 g","price":80},{"id":"v7b","label":"250 g","price":180},{"id":"v7c","label":"500 g","price":320}]',
 21, '/assets/products/3_Turmeric_Powder.png',
 '["/assets/products/3_Turmeric_Powder.png","/assets/products/3_Turmeric_Powder_1.png"]',
 NOW(), NOW()),

('8', 'Cardamom (Elaichi)', 'इलायची', 140, 'Spices',
 '8mm bold, lush green cardamom pods from the Idukki hills of Kerala. Packed with essential oils for an unmatched aroma.',
 'केरल की पहाड़ियों से प्राप्त 8mm बोल्ड हरी इलायची। लाजवाब खुशबू के लिए प्राकृतिक तेलों से भरपूर।',
 'Madhuban Spices', 'Kerala, India',
 '["Whole Green Cardamom"]',
 '["Excellent natural mouth freshener","Aids in digestion and reduces acidity","Helps in detoxifying the body through kidneys","Traditionally used for blood pressure management"]',
 '["बेहतरीन प्राकृतिक माउथ फ्रेशनर","पाचन में सुधार और एसिडिटी कम करता है","किडनी के माध्यम से शरीर को डिटॉक्स करता है","ब्लड प्रेशर नियंत्रित करने में सहायक"]',
 '["FSSAI"]', '0909', 5,
 '[{"id":"v8a","label":"25 g","price":140},{"id":"v8b","label":"50 g","price":260},{"id":"v8c","label":"100 g","price":480}]',
 16, '/assets/products/4_Cardamom.png',
 '["/assets/products/4_Cardamom.png","/assets/products/4_Cardamom_1.png"]',
 NOW(), NOW()),

('9', 'Cumin (Jira) Seeds', 'साबुत जीरा', 50, 'Spices',
 'Selected premium quality Cumin seeds from Unjha, Gujarat. These seeds are machine-cleaned and hand-graded for the perfect ''Tadka''.',
 'गुजरात के उंझा से प्राप्त प्रीमियम गुणवत्ता वाला जीरा। बेहतरीन तड़के के लिए मशीनी सफाई और हैंड-ग्रेडिंग की गई।',
 'Madhuban Spices', 'Gujarat, India',
 '["Whole Cumin Seeds"]',
 '["Contains Thymol which stimulates digestive enzymes","Rich source of Iron for energy and immunity","Helpful in managing blood sugar levels","Aids weight loss by improving metabolism"]',
 '["थाइमोल युक्त जो पाचन एंजाइमों को उत्तेजित करता है","ऊर्जा और इम्युनिटी के लिए आयरन का समृद्ध स्रोत","ब्लड शुगर लेवल को नियंत्रित करने में सहायक","मेटाबॉलिज्म सुधारकर वजन घटाने में मदद करता है"]',
 '["FSSAI"]', '0909', 5,
 '[{"id":"v9a","label":"100 g","price":50},{"id":"v9b","label":"250 g","price":100},{"id":"v9c","label":"500 g","price":180}]',
 28, '/assets/products/5_Cumin_Seeds.png',
 '["/assets/products/5_Cumin_Seeds.png","/assets/products/5_Cumin_Seeds_1.png"]',
 NOW(), NOW()),

('10', 'Cinnamon (Dalchini) Sticks', 'दालचीनी', 140, 'Spices',
 'Premium sweet-scented Cinnamon sticks. Unlike common Cassia, our bark is chosen for its thin layers and delicate, non-bitter flavor.',
 'प्रीमियम खुशबूदार दालचीनी की छड़ें। अपनी पतली परतों और मीठे स्वाद के लिए चुनी गई।',
 'Madhuban Spices', 'Sri Lanka/South India',
 '["Pure Cinnamon Bark"]',
 '["Improves insulin sensitivity (great for diabetics)","Reduces bad cholesterol (LDL)","Natural breath freshener and oral health booster","Anti-viral properties help fight common colds"]',
 '["इंसुलिन संवेदनशीलता सुधारता है (मधुमेह रोगियों के लिए अच्छा)","खराब कोलेस्ट्रॉल (LDL) को कम करता है","प्राकृतिक माउथ फ्रेशनर और ओरल हेल्थ बूस्टर","सामान्य सर्दी से लड़ने में एंटी-वायरल गुण"]',
 '["FSSAI"]', '0906', 5,
 '[{"id":"v10a","label":"50 g","price":140},{"id":"v10b","label":"100 g","price":260},{"id":"v10c","label":"250 g","price":600}]',
 18, '/assets/products/6_Cinnamon_Sticks.png',
 '["/assets/products/6_Cinnamon_Sticks.png","/assets/products/6_Cinnamon_Sticks_1.png"]',
 NOW(), NOW()),

('11', 'Black Pepper (Kali Mirch)', 'काली मिर्च', 120, 'Spices',
 'Grown in the Malabar coast, these peppercorns are sun-dried and graded for maximum Piperine content, which provides the real heat.',
 'मालाबार तट से प्राप्त, ये काली मिर्च धूप में सुखाई गई हैं और असली तीखेपन (पाइपरिन) के लिए प्रसिद्ध हैं।',
 'Madhuban Spices', 'Kerala, India',
 '["Whole Black Peppercorns"]',
 '["Enhances nutrient absorption (especially Curcumin)","Improves brain function and cognitive health","Stimulates hydrochloric acid in the stomach for digestion","Rich in Manganese and Vitamin K"]',
 '["पोषक तत्वों (विशेषकर हल्दी) के अवशोषण को बढ़ाता है","मस्तिष्क कार्यप्रणाली और मानसिक स्वास्थ्य में सुधार","पाचन के लिए पेट में एसिड को उत्तेजित करता है","मैंगनीज और विटामिन K का अच्छा स्रोत"]',
 '["FSSAI"]', '0904', 5,
 '[{"id":"v11a","label":"100 g","price":120},{"id":"v11b","label":"200 g","price":220},{"id":"v11c","label":"500 g","price":500}]',
 22, '/assets/products/7_Black_Pepper.png',
 '["/assets/products/7_Black_Pepper.png","/assets/products/7_Black_Pepper_1.png"]',
 NOW(), NOW()),

('12', 'Coriander Seeds (Dhaniya)', 'साबुत धनिया', 50, 'Spices',
 'Lush green coriander seeds with a distinct citrusy notes. Sourced from the fields of Madhya Pradesh, perfect for home-ground masalas.',
 'मध्य प्रदेश के खेतों से प्राप्त, विशेष खट्टेपन वाली खुशबू वाले धनिया बीज। घर में बने मसालों के लिए उत्तम।',
 'Madhuban Spices', 'Madhya Pradesh, India',
 '["100% Whole Coriander Seeds"]',
 '["Natural diuretic that helps reduce water retention","Excellent for cooling the body in summers","Helps regulate menstrual flow and symptoms","Improves hair growth by strengthening roots"]',
 '["प्राकृतिक मूत्रवर्धक जो शरीर की सूजन कम करता है","गर्मियों में शरीर को ठंडा रखने के लिए बेहतरीन","मासिक धर्म चक्र को विनियमित करने में सहायक","जड़ों को मजबूत कर बालों के विकास में सुधार"]',
 '["FSSAI"]', '0909', 5,
 '[{"id":"v12a","label":"100 g","price":50},{"id":"v12b","label":"250 g","price":100},{"id":"v12c","label":"500 g","price":140}]',
 26, '/assets/products/8_Coriander_Seeds.png',
 '["/assets/products/8_Coriander_Seeds.png","/assets/products/8_Coriander_Seeds_1.png"]',
 NOW(), NOW()),

('13', 'Fenugreek Seeds (Methi)', 'मेथी दाना', 40, 'Spices',
 'High-quality bitter-sweet Methi seeds. Essential for the classic Indian tempering and pickling.',
 'उच्च गुणवत्ता वाले खट्टे-मीठे मेथी के बीज। भारतीय तड़के और अचार बनाने के लिए अनिवार्य।',
 'Madhuban Spices', 'Rajasthan, India',
 '["100% Whole Fenugreek Seeds"]',
 '["Proven to help manage blood sugar (diabetes control)","Excellent for lactating mothers to boost milk production","Reduces heartburn and acid reflux","Traditional remedy for dandruff and hair loss"]',
 '["ब्लड शुगर (मधुमेह) को नियंत्रित करने में सिद्ध","स्तनपान कराने वाली माताओं में दूध उत्पादन बढ़ाने के लिए उत्तम","सीने की जलन और एसिड रिफ्लक्स को कम करता है","डैंड्रफ और बालों के झड़ने के लिए पारंपरिक उपचार"]',
 '["FSSAI"]', '0911', 5,
 '[{"id":"v13a","label":"50 g","price":40},{"id":"v13b","label":"100 g","price":75},{"id":"v13c","label":"250 g","price":110}]',
 30, '/assets/products/9_Fenugreek_Seeds_1.png',
 '["/assets/products/9_Fenugreek_Seeds_1.png","/assets/products/9_Fenugreek_Seeds_1.png"]',
 NOW(), NOW()),

('14', 'Cloves (Laung)', 'लौंग', 120, 'Spices',
 'Large, full-headed cloves with high volatile oil content. Hand-sorted to remove stems and dust.',
 'उच्च तेल सामग्री वाली बड़ी और साबुत लौंग। डंठल और धूल हटाने के लिए हाथ से चुनी गई।',
 'Madhuban Spices', 'Kerala/Tamil Nadu, India',
 '["100% Whole Cloves"]',
 '["Contains Eugenol, a natural anesthetic for dental pain","High concentration of antioxidants","Improves liver health and bone density","Helps clear congestion and sore throat"]',
 '["दांत दर्द के लिए प्राकृतिक एनेस्थेटिक (यूजेनॉल) युक्त","एंटीऑक्सीडेंट का उच्च सांद्रण","लिवर स्वास्थ्य और हड्डियों की मजबूती में सुधार","कफ और गले की खराश दूर करने में सहायक"]',
 '["FSSAI"]', '0907', 5,
 '[{"id":"v14a","label":"25 g","price":120},{"id":"v14b","label":"50 g","price":190},{"id":"v14c","label":"100 g","price":300}]',
 15, '/assets/products/10_Cloves_1.png',
 '["/assets/products/10_Cloves_1.png","/assets/products/10_Cloves_1.png"]',
 NOW(), NOW()),

('15', 'Bay Leaves (Tej Patta)', 'तेज पत्ता', 40, 'Spices',
 'Selected dried Bay leaves from the Himalayan foothills. Greenish-olive in color, these leaves offer a subtle fragrance that deepens over slow cooking.',
 'हिमालय की तराई से प्राप्त सूखे तेज पत्ते। इनका हल्का सुगंधित स्वाद धीमी आंच पर पकने वाले व्यंजनों में निखरता है।',
 'Madhuban Spices', 'Uttarakhand/North East India',
 '["100% Dried Bay Leaves"]',
 '["Helps lower blood sugar levels","Enzymes aid in the breakdown of proteins for digestion","Anti-fungal and anti-inflammatory properties","Traditional remedy for stress and anxiety"]',
 '["ब्लड शुगर लेवल कम करने में सहायक","पाचन के लिए प्रोटीन तोड़ने में मदद करने वाले एंजाइम युक्त","एंटी-फंगल और सूजन-रोधी गुण","तनाव और चिंता के लिए पारंपरिक उपचार"]',
 '["FSSAI"]', '0907', 5,
 '[{"id":"v15a","label":"10 g","price":40},{"id":"v15b","label":"25 g","price":80},{"id":"v15c","label":"50 g","price":90}]',
 20, '/assets/products/11_Bay_Leaves_1.png',
 '["/assets/products/11_Bay_Leaves_1.png","/assets/products/11_Bay_Leaves_2.png"]',
 NOW(), NOW()),

('16', 'Fennel Seeds (Saunf)', 'सौंफ', 40, 'Spices',
 'Sweet, thin, and intensely aromatic Lucknowi Saunf. Perfectly sun-dried to maintain its vibrant green color and digestive oils.',
 'मीठी, पतली और अत्यधिक सुगंधित लखनवी सौंफ। इसके हरे रंग और पाचन तेलों को बनाए रखने के लिए धूप में सुखाई गई।',
 'Madhuban Spices', 'Uttar Pradesh, India',
 '["100% Pure Fennel Seeds"]',
 '["Relieves bloating, gas, and indigestion","Purifies blood and regulates blood pressure","Helps in improving eyesight (traditional belief)","Excellent for freshening breath and oral hygiene"]',
 '["पेट फूलना, गैस और अपच से राहत","रक्त को शुद्ध करता है और ब्लड प्रेशर नियंत्रित करता है","आंखों की रोशनी सुधारने में सहायक (पारंपरिक मान्यता)","सांसों की ताजगी और ओरल हाइजीन के लिए उत्तम"]',
 '["FSSAI"]', '0909', 5,
 '[{"id":"v16a","label":"50 g","price":40},{"id":"v16b","label":"100 g","price":80},{"id":"v16c","label":"250 g","price":130}]',
 18, '/assets/products/12_Fennel_Seeds_1.png',
 '["/assets/products/12_Fennel_Seeds_1.png","/assets/products/12_Fennel_Seeds_1.png"]',
 NOW(), NOW()),

('17', 'Saffron (Kesar)', 'केसर', 250, 'Spices',
 'World-class Grade A++ Mongra Saffron from Pampore, Kashmir. Deep red stigmas only, providing rich color, aroma, and therapeutic value.',
 'कश्मीर के पंपोर से प्राप्त विश्व स्तरीय ग्रेड A++ मोंगरा केसर। बेहतरीन रंग और औषधीय गुणों के लिए केवल गहरे लाल धागे।',
 'Madhuban Spices', 'Kashmir, India',
 '["100% Pure Saffron Stigmas"]',
 '["Natural mood booster and antidepressant properties","Rich in Crocin which improves memory and brain health","Supports skin health and natural glow","Traditionally used during pregnancy for wellness"]',
 '["प्राकृतिक मूड बूस्टर और एंटी-डिप्रेसेंट","क्रॉसिन से भरपूर जो याददाश्त और दिमाग को तेज करता है","त्वचा के स्वास्थ्य और प्राकृतिक चमक में सहायक","गर्भावस्था के दौरान स्वास्थ्य के लिए पारंपरिक रूप से उपयोग"]',
 '["Organic","FSSAI"]', '0916', 5,
 '[{"id":"v17a","label":"0.25 g","price":250},{"id":"v17b","label":"0.5 g","price":500},{"id":"v17c","label":"1 g","price":950}]',
 5, '/assets/products/13_Saffron_1.png',
 '["/assets/products/13_Saffron_1.png","/assets/products/13_Saffron_2.png"]',
 NOW(), NOW()),

('18', 'Red Chilli Powder (Lal Mirch)', 'लाल मिर्च पाउडर', 85, 'Spices',
 'Pure red chilli powder with a balance of heat and color. Sourced from Guntur, Andhra Pradesh. Free from added colors or oils.',
 'तीखेपन और रंग का सही संतुलन। आंध्र प्रदेश के गुंटूर से प्राप्त। बिना किसी मिलावटी रंग या तेल के।',
 'Madhuban Spices', 'Andhra Pradesh, India',
 '["100% Ground Red Chillies"]',
 '["Capsaicin helps boost metabolism and burn fat","Rich in Vitamin C for immunity","Helps clear congestion and sinus issues","Supports cardiovascular health by improving circulation"]',
 '["कैप्साइसिन मेटाबॉलिज्म और वजन घटाने में सहायक","इम्युनिटी के लिए विटामिन सी से भरपूर","साइनस और बंद नाक खोलने में मदद करता है","रक्त संचार सुधारकर हृदय स्वास्थ्य का समर्थन"]',
 '["FSSAI"]', '0904', 5,
 '[{"id":"v18a","label":"100 g","price":85},{"id":"v18b","label":"200 g","price":150},{"id":"v18c","label":"500 g","price":350}]',
 19, '/assets/products/14_Red_Chilli_Powder_1.png',
 '["/assets/products/14_Red_Chilli_Powder_1.png","/assets/products/14_Red_Chilli_Powder_2.png"]',
 NOW(), NOW());

-- Optional: keep product rows unique if re-run across environments
-- ON CONFLICT (id) DO UPDATE SET
--     name = EXCLUDED.name,
--     name_hi = EXCLUDED.name_hi,
--     price = EXCLUDED.price,
--     category = EXCLUDED.category,
--     description = EXCLUDED.description,
--     description_hi = EXCLUDED.description_hi,
--     manufacturer = EXCLUDED.manufacturer,
--     origin = EXCLUDED.origin,
--     ingredients = EXCLUDED.ingredients,
--     health_benefits = EXCLUDED.health_benefits,
--     health_benefits_hi = EXCLUDED.health_benefits_hi,
--     certifications = EXCLUDED.certifications,
--     hsn_code = EXCLUDED.hsn_code,
--     gst_rate = EXCLUDED.gst_rate,
--     variants = EXCLUDED.variants,
--     stock = EXCLUDED.stock,
--     image = EXCLUDED.image,
--     images = EXCLUDED.images,
--     updated_at = NOW();
